// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with  Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBivlheCj29kRmCbuZZ3x8Vv5-VmDkYk4A',
    appId: '1:119447144476:web:4beda0430a52db2610b7d9',
    messagingSenderId: '119447144476',
    projectId: 'programit-app',
    authDomain: 'programit-app.firebaseapp.com',
    storageBucket: 'programit-app.firebasestorage.app',
    measurementId: 'G-E3RXZGBHHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DBoAq2WqqTYXTzPAoR1-GaMvkzKxjdc',
    appId: '1:119447144476:android:b6c4be8d4663e52b10b7d9',
    messagingSenderId: '119447144476',
    projectId: 'programit-app',
    storageBucket: 'programit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHMNs3IzNH5FDLBV6B8DfVaAmWsTqiBo',
    appId: '1:119447144476:ios:01188744b3db153d10b7d9',
    messagingSenderId: '119447144476',
    projectId: 'programit-app',
    storageBucket: 'programit-app.firebasestorage.app',
    iosBundleId: 'com.example.programmitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFHMNs3IzNH5FDLBV6B8DfVaAmWsTqiBo',
    appId: '1:119447144476:ios:01188744b3db153d10b7d9',
    messagingSenderId: '119447144476',
    projectId: 'programit-app',
    storageBucket: 'programit-app.firebasestorage.app',
    iosBundleId: 'com.example.programmitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8arqKRguuXnxpgeTcfGfTY84XizJ7nAg',
    appId: '1:119447144476:web:0a698017a1551a1110b7d9',
    messagingSenderId: '119447144476',
    projectId: 'programit-app',
    authDomain: 'programit-app.firebaseapp.com',
    storageBucket: 'programit-app.firebasestorage.app',
    measurementId: 'G-YNNQGW8R61',
  );
}
